sudo:required
services:
    - docker

before_install:
    - docker build -t notagiant93/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true notagiant93/react-test npm run test

after_success:
    - docker build -t notagiant93/multi-client ./client
    - docker build -t notaginat93/multi-nginx ./nginx
    - docker build -t notaginat93/multi-server ./server
    - docker build -t notaginat93/multi-woker ./worker
    #Login to the Docker CLI
    -echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

    #Take those images and push those to Docker hub
    - docker push notagiant93/multi-client
    - docker push notaginat93/multi-nginx
    - docker push notaginat93/multi-server
    - docker push notaginat93/multi-woker